-- Добавляем новые категории
INSERT INTO t_p61788166_html_to_frontend.categories (name, icon) VALUES
  ('Облачная инфраструктура / Хостинг', 'Cloud'),
  ('Серверная инфраструктура', 'Server'),
  ('Телефония / Виртуальная АТС', 'Phone'),
  ('Виртуальные SIM / Телефония', 'Smartphone'),
  ('Домены и корпоративная почта', 'Mail'),
  ('Подписки / Медиа и коммуникации', 'Rss'),
  ('Мессенджеры / Коммуникационные сервисы', 'MessageSquare'),
  ('AI-сервисы / Разработка и автоматизация', 'Bot'),
  ('AI-подписка / Операционная деятельность', 'Sparkles'),
  ('Домены', 'Globe'),
  ('Домены и хостинг', 'Globe'),
  ('Домены сайтов / Маркетинг', 'Globe'),
  ('SMS-сервисы / Регистрация аккаунтов', 'MessageCircle'),
  ('Мобильная связь', 'Signal'),
  ('Видеоконференции / Корпоративная связь', 'Video'),
  ('Проверка контрагентов / Юридические сервисы', 'Shield'),
  ('Мобильная связь / Телефония', 'PhoneCall'),
  ('Виртуальная АТС / Телефония', 'PhoneForwarded'),
  ('Маркетинг / Рекламная аналитика', 'BarChart2'),
  ('SMS-рассылки / Контакт-центр', 'Send'),
  ('Маркетинговая аналитика / Коллтрекинг', 'TrendingUp'),
  ('BI-аналитика / Управленческая отчетность', 'PieChart'),
  ('Телефония / Интеграции контакт-центра', 'Headphones');

-- Добавляем новые сервисы
-- Используем подзапросы для получения id категорий по имени
INSERT INTO t_p61788166_html_to_frontend.services (name, description, category_id) VALUES
  ('Timeweb Cloud', 'Серверы для банков и бухгалтерии', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Облачная инфраструктура / Хостинг' LIMIT 1)),
  ('1Dedic', 'Основные сервера: 1С, Битрикс, RDP и др.', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Серверная инфраструктура' LIMIT 1)),
  ('Mango Office', 'Резервная телефония контактного центра', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Телефония / Виртуальная АТС' LIMIT 1)),
  ('Плюсофон', 'Виртуальные сим-карты', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Виртуальные SIM / Телефония' LIMIT 1)),
  ('Timeweb 2', 'Домен dreamteamcompany.ru', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены и корпоративная почта' LIMIT 1)),
  ('Telegram Предприниматели Патриоты', 'Подписка Telegram', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Подписки / Медиа и коммуникации' LIMIT 1)),
  ('Wazzup', 'Интеграция мессенджеров', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мессенджеры / Коммуникационные сервисы' LIMIT 1)),
  ('OpenAI', 'Использование ИИ для команды', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'AI-сервисы / Разработка и автоматизация' LIMIT 1)),
  ('ChatGPT', 'Рабочая подписка команды', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'AI-подписка / Операционная деятельность' LIMIT 1)),
  ('Timeweb 3', 'Домен permdental.ru', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены' LIMIT 1)),
  ('Timeweb 4', 'Домен omskdental.ru', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены' LIMIT 1)),
  ('Timeweb 1', 'Домен server.server41.ru', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены' LIMIT 1)),
  ('Рег.ру 1', 'Корпоративная почта и домены', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены и хостинг' LIMIT 1)),
  ('Рег.ру 2', 'Домены маркетинговых сайтов', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Домены сайтов / Маркетинг' LIMIT 1)),
  ('SmsFast', 'Иностранные SIM для регистрации', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'SMS-сервисы / Регистрация аккаунтов' LIMIT 1)),
  ('iSpring', 'Система обучения сотрудников', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Обучение' LIMIT 1)),
  ('Сим-карты Предприниматели Патриоты (ООО)', 'Корпоративные SIM', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мобильная связь' LIMIT 1)),
  ('Сим-карты Предприниматели Патриоты (ИП)', 'Корпоративные SIM', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мобильная связь' LIMIT 1)),
  ('Сим-карты МТС (СПБ)', 'Корпоративные SIM МТС Санкт-Петербург', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мобильная связь' LIMIT 1)),
  ('Сим-карты МТС (Краснодар)', 'Корпоративные SIM МТС Краснодар', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мобильная связь' LIMIT 1)),
  ('Zoom 1', 'Видеоконференции', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Видеоконференции / Корпоративная связь' LIMIT 1)),
  ('Zoom 2', 'Видеоконференции', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Видеоконференции / Корпоративная связь' LIMIT 1)),
  ('Контур Фокус', 'Проверка контрагентов', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Проверка контрагентов / Юридические сервисы' LIMIT 1)),
  ('Билайн Этикетка ЛК', 'Мобильная связь Билайн', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Мобильная связь / Телефония' LIMIT 1)),
  ('Билайн Этикетка ОАТС', 'Виртуальная АТС Билайн', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Виртуальная АТС / Телефония' LIMIT 1)),
  ('MyBI Connect', 'Рекламная аналитика', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Маркетинг / Рекламная аналитика' LIMIT 1)),
  ('Касперский Password Manager', 'Управление паролями и доступами', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Информационная безопасность' LIMIT 1)),
  ('SMS.RU', 'SMS-рассылки контакт-центра', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'SMS-рассылки / Контакт-центр' LIMIT 1)),
  ('Calltouch', 'Маркетинговая аналитика и коллтрекинг', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Маркетинговая аналитика / Коллтрекинг' LIMIT 1)),
  ('Power BI 1', 'BI-аналитика и управленческая отчетность', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'BI-аналитика / Управленческая отчетность' LIMIT 1)),
  ('Power BI 2', 'BI-аналитика и управленческая отчетность', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'BI-аналитика / Управленческая отчетность' LIMIT 1)),
  ('Voximplant Control Panel', 'Телефония и интеграции контакт-центра', (SELECT id FROM t_p61788166_html_to_frontend.categories WHERE name = 'Телефония / Интеграции контакт-центра' LIMIT 1));
